version: "3"
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    tty: true
    volumes:
      - ./:/app
    ports:
      - "80:80"
    command: cargo run
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: Sa01
      POSTGRES_USER: sa
      POSTGRES_DB: template