FROM rust:1.66.1
WORKDIR /app
RUN rustup target add x86_64-unknown-linux-musl
RUN rustup component add rustfmt
RUN cargo install cargo-watch cargo-make
RUN cargo install sqlx-cli --no-default-features --features native-tls,postgres
RUN apt-get update && apt-get install postgresql-client -y